"""initial admin schema

Revision ID: ff395fe1c93f
Revises: 
Create Date: 2026-06-14 16:51:12.454359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff395fe1c93f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('client_name', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('lead_score', sa.Text(), nullable=True),
    sa.Column('from_stage', sa.Text(), nullable=True),
    sa.Column('to_stage', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_client_events_client_id_created_at', 'client_events', ['client_id', 'created_at'], unique=False, postgresql_using='btree')
    op.create_index('idx_client_events_event_type_created_at', 'client_events', ['event_type', 'created_at'], unique=False, postgresql_using='btree')
    op.create_table('client_registry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('client_name', sa.Text(), nullable=False),
    sa.Column('railway_url', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_registry')
    op.drop_index('idx_client_events_event_type_created_at', table_name='client_events', postgresql_using='btree')
    op.drop_index('idx_client_events_client_id_created_at', table_name='client_events', postgresql_using='btree')
    op.drop_table('client_events')
    # ### end Alembic commands ###
